routes/web.php
<?php

use App\Tasks\Users;
use Illuminate\Support\Facades\Hash;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

\URL::forceScheme('https');
 URL::forceRootUrl(env('APP_URL'));

Route::get('/', [
    'as'    => 'forum.home',
    'uses'  => 'ForumThreadController@index'
]);



Auth::routes();
Route::get('register', 'Auth\RegisterController@showRegistrationForm')
    ->name('register')
    ->middleware('has.token');

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');

Route::get('/home', 'HomeController@index')->name('home');


//========================= Forum ========================================

//store user thread subcription
Route::post('forum/threads/{channel}/{thread}/subscription', 'ForumThreadSubscriptionController@store')->middleware('auth');

//delete user thread subcription
Route::delete('forum/threads/{channel}/{thread}/subscription', 'ForumThreadSubscriptionController@destroy')->middleware('auth');


//get all the thread replies
Route::get('/forum/threads/{channel}/{thread}/replies','ForumReplyController@index');

Route::patch('forum/replies/{reply}', 'ForumReplyController@update')->middleware('auth');

//deleting a reply
Route::delete('forum/replies/{reply}', 'ForumReplyController@destroy')->middleware('auth');

//showcase all the threads
Route::get('threads', 'ForumThreadController@index');
Route::get('threads/{channel}', 'ForumThreadController@index');

//showcase all the threads
Route::get('forum/threads', 'ForumThreadController@index');

//create a forum thread
Route::get('forum/threads/create', 'ForumThreadController@create')->name('new.discussion')->middleware('auth');

//a user can delete their threads
Route::delete('forum/threads/{channel}/{thread}', 'ForumThreadController@destroy')->middleware('auth');

//showcase all the channel's thread
Route::get('forum/threads/{channel}', 'ForumThreadController@index');

//post a thread
Route::post('forum/threads', 'ForumThreadController@store')->middleware('auth');

//showcase a spefici channel thread
//showcase all the channel's thread
Route::get('forum/threads/{channel}/{thread}', 'ForumThreadController@show');

//update a thread
Route::patch('forum/threads/{channel}/{thread}', 'ForumThreadController@update');

//post a reply to a thread
Route::post('forum/threads/{channel}/{thread}/replies', 'ForumReplyController@store')->middleware('auth');

// mark a favorite reply
Route::post('/forum/replies/{reply}/favorites','ForumFavoriteController@store')->middleware('auth');

//delete a favorited reply
Route::delete('/forum/replies/{reply}/favorites','ForumFavoriteController@destroy')->middleware('auth');

// showing the user profile
Route::get('forum/profiles/{user}', 'ForumProfileController@show');

// showing the user notifications
Route::get('forum/profiles/{user}/notifications', 'NotificationController@index');

// marking a notification as read
Route::delete('forum/profiles/{user}/notifications/{notification}', 'NotificationController@destroy')->middleware('auth');

//mark the best reply of a thread
Route::post('forum/replies/{reply}/best', 'BestReplyController@store')->middleware('auth');

Route::get('api/users/list', function(){
  return Users::all();
});


Route::post('/upload/user/avatar', 'UserController@store')->middleware('auth');

//========================== Forum Ended ========================================

// ============================= shopify ===========================================
Route::prefix('/shopify')->middleware('odin')->group(function () {
    // ----- entry point for app
    Route::get('/', [
      'as'    => 'shopify.landing-page',
      'uses'  => 'ShopifyController@access'
    ])->middleware('payment')->middleware('hades');

    // ----- auth callback
    Route::get('auth-callback', [
      'as' => 'shopify.auth-callback',
      'uses' => 'ShopifyController@authCallback'
    ])->middleware('payment');

    // ----- uninstall hook callback
    Route::post('hooks/uninstall', [
      'as' => 'shopify.hooks-uninstall',
      'uses'  => 'ShopifyController@uninstall'
    ]);

    Route::get('/proxy', [
        'as' => 'shopify.proxy',
        'uses'  => 'ShopifyController@proxy'
    ]);
});

// ----- payment confirmation
Route::get('/shopify/charge-callback', [
  'as' => 'shopify.charge-callback',
  'uses' => 'ShopifyController@chargeCallback'
])->middleware('payment');


// ============================= shopify ended ===========================================

// ================================ admin & publisher ===================================================

Route::get('/{any}', 'Admin\AdminController@index')->where('any', 'admin')->middleware('is.grant');

use Illuminate\Routing\Router;

Route::group([
    'prefix'        => 'api',
    'namespace'     => 'Admin',
    'middleware'    => 'is.grant',
], function (Router $router) {

    Route::get('/channels', 'ForumChannelController@index');
    Route::patch('/channels', 'ForumChannelController@update');
    Route::post('/channels', 'ForumChannelController@store');
    Route::get('/channels/count', function(){
        return \App\Services\Stats\Channels::count();
    });
    Route::get('/channels/total/theads', function(){
        return \App\Services\Stats\Channels::totalThreads();
    });

    Route::get('/threads', 'ForumThreadController@index');
    Route::patch('/threads', 'ForumThreadController@update');
    Route::patch('/ban/thread', 'ForumThreadController@ban');
    Route::get('/threads/count', function(){
        return \App\Services\Stats\Threads::count();
    });
    Route::get('/threads/with/no/replies', function(){
        return \App\Services\Stats\Threads::noReplies();
    });
    Route::get('/trending/threads', function(){
        $trending_thread = new \App\Tasks\Forum\TrendingThreads;
        return $trending_thread();
    });
    Route::get('/recent/thread', function(){
        return \App\Services\Stats\Threads::recent();
    });

    Route::get('/replies', 'ForumReplyController@index');
    Route::patch('/replies', 'ForumReplyController@update');
    Route::patch('/ban/reply', 'ForumReplyController@ban');
    Route::get('/replies/count', function(){
        return \App\Services\Stats\Replies::count();
    });
    Route::get('/recent/reply', function(){
        return \App\Services\Stats\Replies::recent();
    });

    Route::get('/publishers', 'ForumPublisherController@index');
    Route::post('/publisher', 'ForumPublisherController@store');
    Route::patch('/publisher', 'ForumPublisherController@update');

    Route::get('/members', 'ForumMemberController@index');
    Route::post('/member', 'ForumMemberController@store');
    Route::patch('/ban/member', 'ForumMemberController@ban');
    Route::get('/members/count', function(){
        return  \App\Services\Stats\Members::count();
    });
    Route::get('/top/members', function(){
        return \App\Services\Stats\Members::top();
    });
    Route::get('/recent/member', function(){
        return \App\Services\Stats\Members::recent();
    });

    //get the store settings
    Route::get('/branding', 'ForumBrandingController@index');
    Route::patch('/branding', 'ForumBrandingController@update');
    Route::post('/branding', 'ForumBrandingController@store');

    Route::get('/themes', 'ForumThemeController@index');

    Route::get('/theme/settings', 'ForumThemeSettingController@show');
    Route::patch('/theme/settings', 'ForumThemeSettingController@update');


    Route::patch('/shop/appearance', 'ForumAppearanceController@update');
    Route::post('/shop/appearance', 'ForumAppearanceController@store');

    Route::get('/account/details', function(){
        return \App\Repository\Forum\UserAccount::get();
    });
    Route::post('/account/details', function(){
        return \App\Repository\Forum\UserAccount::update();
    });

    Route::get('/shop/plan/features', function (){

        return \App\Services\ShopPlanFeatures::get();
    });


});

// ================================ admin & publisher ended ===================================================

// ================================ admin  ===================================================
Route::group([
    'prefix'        => 'api',
    'namespace'     => 'Admin',
    'middleware'    => 'is.admin',
], function (Router $router) {

    Route::get('/publishers', 'ForumPublisherController@index')->name('team.users');
//    Route::post('/publisher', 'ForumPublisherController@store');
    Route::patch('/publisher', 'ForumPublisherController@update');

    Route::post('/invitation', 'ForumInviteController@invite')->name('sendInvitation')->middleware('can.invite.team.users');

});
// ================================ admin ended ===================================================

Route::get('/api/shop/appearance', 'Admin\ForumAppearanceController@show')->name('shopAppearance');

app/ForumThread.php
<?php

namespace App;

use App\Scopes\ShopScope;
use Illuminate\Database\Eloquent\Model;
use App\ForumChannel;
use App\Traits\RecordForumActivity;
use App\ForumThreadSubscription;
use Illuminate\Support\Facades\Auth;
use App\Notifications\ThreadWasUpdated;
use App\Events\ThreadHasNewReply;
use App\Visits;
use App\ForumReply;
use Illuminate\Support\Facades\Cache;
use Stevebauman\Purify\Purify;

class ForumThread extends Model
{
    use RecordForumActivity;

    protected $guarded = [] ;

    protected $appends = ['isSubscribedTo'];

    /**
     * The "booting" method of the model.
     * Global Query scope
     *Adding the constraint of the shop id
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ShopScope);
    }

    public function getRouteKeyName(){

        return 'slug';
    }

    public function getReplyCountAttribute(){

        return $this->replies()->count();

    }

    public function path(){

        return "/threads/{$this->channel->slug}/{$this->slug}";  // adddin a slug channel name i.e threads/php/1

    }
    public function replies(){

        return $this->hasMany(ForumReply::class)->withCount('favorites');
    }

    public function creator(){

        // as i am using the owner name instead of user,
        // so i am being explicit for the model key which then i have specificed user_id
        return $this->belongsTo(User::class, 'user_id');
    }

    public function addReply($reply){

        $reply = $this->replies()->create($reply); // this->replihipd deletages to the older relationship

        event(new ThreadHasNewReply($this, $reply));

        //$this->notifySubscribers($reply);

        return $reply;
    }

    public function channel(){

        return $this->belongsTo(ForumChannel::class, 'forum_channel_id');
    }


    public function subscribe(){

        $this->subscriptions()->create([
            'shop_id' => Cache::get('shop_id'),
            'user_id' => Auth::id()

        ]);

    }

    public function unsubscribe(){

        $user_id = Auth::id();

        return $this->subscriptions()->where('user_id', $user_id)->delete();

    }

    public function subscriptions(){

       return  $this->hasMany(ForumThreadSubscription::class);

    }

    public function getIsSubscribedToAttribute(){

        $user_id = Auth::id();

        $exists =  $this->subscriptions()
                    ->where('user_id',$user_id)
                    ->exists();

        return $exists ? 1 : 0;

    }

    public function hasUpdatesFor($user = null){



        // $user = $user ?: Auth::user();

        // $key = sprintf("users.%s.visits.%s", Auth::id(), $this->id);

        $key = Auth::user()->visitedThreadCacheKey($this);

        return $this->updated_at > cache($key);

    }

    public function visits(){

        return new Visits($this);
    }

    public function setSlugAttribute($value){

        if(static::whereSlug($value)->exists()){

            $latestModelId = Static::max('id');

            $this->attributes['slug'] = $value . '-' . ++$latestModelId;

        }else{

            $this->attributes['slug'] = $value;

        }

    }

    public function markAsBest(ForumReply $reply){

        $this->update([
            'best_forum_reply_id' => $reply->id
        ]);
    }

    public function recentReply(){

        return $this->replies()->latest()->first();
    }

    public function getBodyAttribute($body){

        return \Purify::clean($body);
    }
}

resources/views/forum/threads/create.blade.php
@extends('layouts.forum')
@section('title', 'Create a Discussion Thread')

@section('page-title')
  @yield('title')
@endsection
@section('page-content')
           <!-- =============== create thread =============== -->
           <script src='https://www.google.com/recaptcha/api.js'></script>

            <div class="row">
    
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
      
                <form class="col-lg-12" action="/forum/threads" method="POST" >
                  @csrf
                  @method('post')

                    <div class="form-group">
                      <label for="title">Title</label>
                      <input type="text" class="form-control"  placeholder="Add a title" name="title" required>
                    
                    </div>
                    <div class="form-group">
                        <label for="body">Discuss</label>
                        {{--  <textarea required class="form-control" id="exampleFormControlTextarea1" rows="8" placeholder="What's on your mind?" name="body"></textarea>
                        
                        --}}

                        <wysiwyg-component name="body"></wysiwyg-component>
                        
                    </div>

                    <div class="form-group">
                     
                      <select class="form-control form-control-lg" name="channel" required>
                        <option value="">Select a channel</option>
                          @foreach ($channels as $channel)
                            <option value="{{$channel->id}}">{{$channel->slug}}</option>
                          @endforeach
                       
                      </select>
                    </div>
                    
                    <div class="g-recaptcha" data-sitekey="6Lc6Np4UAAAAAFh30asYcWo68c-uUNAmwSaPVgZz">


                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
          <!-- =============== create thread ended=============== -->
@endsection

resources/views/forum/threads/index.blade.php
@extends('layouts.forum')
@section('title', 'Threads')

@section('page-title')
  @yield('title')
@endsection

@section('page-content')

    <threads inline-template>

            <div class="row">

                <div class="col-sm-12">
                    @if (request('search'))
                        {{ count($threads) }} results found
                    @endif
                </div>

              @forelse ($threads as $thread)


                <div class="col-sm-12">
                  <div class="card">

                    <div class="card-body">

                      <div class="channelType">

                          <a v-bind:style="[primaryButtonOverrideStyles]" href="/forum/threads/{{$thread->channel->slug}}" class="badge badge-primary"  >{{$thread->channel->slug}}</a>

                      </div>

                      <div class=" row">
                        <div class="col-sm-2">

                            @if( $thread->creator->avatar != '' && strpos($thread->creator->avatar , 'http') !== false)
                                <img src="{{ $thread->creator->avatar }}" class="rounded-circle img-fluid" width="100px"/>
                            @elseif( $thread->creator->avatar != '')

                                <img src="{{Storage::disk("s3")->url($thread->creator->avatar)}}" class="rounded-circle img-fluid" width="100px"/>
                            @else
                                <img src="/img/user-placeholder.jpg" class="rounded-circle img-fluid"  width="100px"/>
                            @endif

                        </div>

                        <div class="col-sm-10">
                          <a href="/forum/threads/{{$thread->channel->slug}}/{{$thread->slug}}">
                            <h5 class="card-title" v-bind:style="[headingOverrideStyles]">

                              @auth

                                @if( $thread->hasUpdatesFor() )

                                  <b> {{$thread->title}}  </b>

                                @else

                                {{$thread->title}}

                              @endif

                            @endauth

                            @guest

                              {{$thread->title}}

                            @endguest

                            </h5>
                          </a>
                            <div class="card-text" v-bind:style="[paragraphOverrideStyles]">{{ strip_tags( str_limit($thread->body, 100) ) }} </div>
                          <br />


                          <span class="commentSpan"> <i class="material-icons outline-comment icon-image-preview">
                            comment
                          </i>{{$thread->replyCount}}</span>


                          <span class="threadAuthor"> Posted By:
                              @if( !empty($thread->creator->alias) )
                                  <a href="/forum/profiles/{{$thread->creator->name}}" v-bind:style="[linkOverrideStyles]">
                                      {{$thread->creator->alias}}
                                  </a>
                                  <span> {{ \Carbon\Carbon::parse($thread->created_at)->diffForHumans() }} </span>
                              @else
                                  <a href="/forum/profiles/{{$thread->creator->name}}" v-bind:style="[linkOverrideStyles]">
                                      {{$thread->creator->name}}
                                  </a>
                                  <span> {{ \Carbon\Carbon::parse($thread->created_at)->diffForHumans() }} </span>
                              @endif

                          </span>

                          <span class="visits"> <i class="material-icons outline-comment icon-image-preview">
                            visibility
                            </i> {{ $thread->visits()->count() }}
                          </span>

                          @if(! empty( $thread->recentReply() ))
                          <div class="col-sm-12 recentReplyInfo">

                            <a href="/forum/profiles/{{$thread->recentReply()['owner']['name']}}"> {{$thread->recentReply()['owner']['name']}} </a>

                              replied

                            <span> {{ \Carbon\Carbon::parse($thread->recentReply()['created_at'])->diffForHumans() }} </span>

                          </div>
                        @endif

                        </div>
                      </div>

                    </div>
                  </div>
                </div>

                @empty
                   <p>No threads created yet for the relevant channel.</p>

              @endforelse

            {{--  =========================== paginate threads ============================= --}}
                @include("forum.threads.paignate")
            {{--                =========================== paginate threads ============================= --}}

            </div>

</threads>
          <!-- =============== training-body ended=============== -->
@endsection

resources/views/forum/threads/paignate.blade.php
        <div class="row indexThreadsPagination">
            <div class="col-sm-12">
                @if(!empty($threads))
                    @if( app('request')->input('by') )
                        {{ $threads->appends(['by' => app('request')->input('by')] )->links() }}
                    @elseif(app('request')->input('fresh'))
                        {{ $threads->appends(['fresh' => 1] )->links() }}
                    @elseif(app('request')->input('search'))
                        {{ $threads->appends(['search' => app('request')->input('search') ] )->links() }}
                    @else
                        {{ $threads->links() }}
                    @endif
                @endif
            </div>
        </div>

resources/views/forum/threads/reply.blade.php
{{--  <forum-reply-component :attributes="{{ $reply }}">  --}}
    <forum-reply-component  :attributes="{{ $reply }}" inline-template v-cloak>

        <div class="col-sm-12">
            <div class="card thread">
        
        
              <div class="card-body">
        
              
        
                <div class=" row" id="reply-{{ $reply->id}}">
                  <div class="col-sm-1"><img src="{{$reply->owner->photo_url}}" class="rounded-circle img-fluid" /></div>
                  <div class ="col-sm-11">
                    <h4 class="threadCreatorHeading">{{$reply->owner->name}} . <span>{{$reply->created_at->diffForHumans()}}</span></h4>
                  </div>
                </div>
                <!-- row ended -->
        
                <div class="row">
                  <div class="col-sm-1"></div>
        
                  <div class="col-sm-11">
                    <p class="card-text" v-if="editing == false">@{{body}}</p>
        
                    <div class="flex">
                      {{--  <form action="/forum/replies/{{$reply->id}}/favorites" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-outline-primary">
                                    
                                    {{$reply->favorites_count}} {{ str_plural('Favorite', $reply->favorites_count )}}
                                  </button>
                      </form>  --}}

                      @auth
                        <favorite-reply-component :reply="{{ $reply }}"></favorite-reply-component>
                      @endauth
                      
                      <br />  <br />
                      
                      @can('update', $reply)
        
        
                      <form v-show="editing">
                          <div class="form-group">
                              <textarea required class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="What's on your mind?" name="body" v-model="body"></textarea>
                          </div>
                          <button type="submit" class="btn btn-primary" @click.prevent="update">Update</button>
                          <button type="submit" class="btn btn-outline-info" @click.prevent="editing = false">Cancel</button>
                      </form>
        
        
                      <button type="submit" class="btn btn-outline-primary" @click="editing = true" v-if="editing == false">Edit</button>
        
                      <div class="flex">
                        <br />
                        {{--  <form class="col-lg-12" action="/forum/replies/{{$reply->id}}" method="POST">
                          @csrf {{method_field('DELETE')}}
                          <button type="submit" class="btn btn-danger">Delete</button>
                        </form>  --}}


                        <button type="submit" class="btn btn-danger" @click="destroy">Delete</button>

                      </div>

                      @endcan
        
        
                    </div>
                  </div>
        
                </div>
                <!-- row ended -->
        
              </div>
              <!-- card-body ended -->
        
        
            </div>
            <!-- card thread ended -->
        
        
          </div>
          <!--col 12 ende -->
    </forum-reply-component>

{{--  
</forum-reply-component>  --}}

resources/views/forum/threads/search.blade.php
<div class="col-sm-9 searchThreadBox">
    <search inline-template value="{{ app('request')->input('search') }}"  >

        <v-app>
            <v-form ref="entryForm" @submit.prevent="search">

                <v-card

                    class="d-flex justify-space-around"
                    color="#f8fafc"
                    flat
                    tile
                >

                    <v-text-field
                        prepend-inner-icon="search"
                        label="Search"
                        class="hidden-sm-and-down"
                        v-model="searchBox"
                        @keyup="change"
                        @submit.prevent="search"
                    >

                    </v-text-field>
                    <v-chip
                        v-if="isSearching"
                        class="ma-2"
                        {{--                                            close--}}
                        @click="clear"
                    >
                        Clear
                    </v-chip>

                </v-card>

            </v-form>

        </v-app>

    </search>
</div>

resources/views/forum/threads/show.old.blade.php
@extends('layouts.forum') 
@section('title', 'Thread Details') 
@section('page-title') @yield('title')
@endsection
 
@section('page-content')
<!-- =============== training-body =============== -->

<div class="row">



  <div class="col-sm-12">
    <div class="card thread">


      <div class="card-body">
        
          <div class="channelType">
            <a href="/forum/threads/{{$thread->channel->slug}}" class="badge badge-primary">{{$thread->channel->slug}}</a>
          </div>

          <div class=" row">
            <div class="col-sm-1"><img src="{{$thread->creator->photo_url}}" class="rounded-circle img-fluid" /></div>
            <div class ="col-sm-11"><h4 class="threadCreatorHeading">{{$thread->creator->name}} . <span>{{$thread->created_at->diffForHumans()}}</span></h4></div>
          </div> <!-- row ended -->

          <div class="row">
            <div class="col-sm-1"></div>
            
            <div class="col-sm-11">
              <h5 class="card-title alert alert-primary">{{$thread->title}}</h5>
          
              <p class="card-text">{{$thread->body}}</p>

              <i class="material-icons outline-comment icon-image-preview">
                  comment
              </i>{{$thread->replyCount}}
              
              @can('update', $thread)
              <div class="flex">
                  <form  action="/forum{{$thread->path()}}" method="POST">
                    @csrf
                    {{method_field('DELETE')}}
                      <button type="submit" class="btn btn-outline-danger">
                        Delete
                    
                      </button>
                  </form>
              </div>
            @endcan
            
            </div>

          </div><!-- row ended -->

      </div> <!-- card-body ended -->


    </div> <!-- card thread ended -->


  </div>

  {{-- 
    =================== thread replies ======================== --}}
    
    @foreach ($replies as $reply)

        @include("forum.threads.reply", $reply)

        @endforeach
        
        {{$replies->links()}}

</div> <!-- row ended -->

<div class="row">

    @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
    @endif

<form class="col-lg-12" action="/forum/threads/{{$thread->channel->id}}/{{$thread->id}}/replies" method="POST">
      @csrf
      @method('post')

       
        <div class="form-group">
            <label for="body">Leave a reply</label>
            <textarea required class="form-control" id="exampleFormControlTextarea1" rows="8" placeholder="What's on your mind?" name="body"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

<!-- =============== training-body ended=============== -->
@endsection